import '../entities/tache.dart';
import '../enums/cible_tache.dart';

/// Contract for persisting and retrieving tasks.
///
/// Reads exclude soft-deleted rows. A task targets exactly one of a potager,
/// parcelle, plantation or equipment ([CibleTache] + cibleId).
///
/// See `docs/05-modele-de-domaine.md` §6.
abstract class AbstractTacheRepository {
  /// Tasks attached to a given target.
  Future<List<Tache>> obtenirParCible(CibleTache cible, String cibleId);

  Future<Tache?> obtenirParId(String id);

  /// Tasks whose planned date falls within `[debut, fin]` (inclusive),
  /// ordered by planned date — feeds the calendar and the daily dashboard.
  Future<List<Tache>> obtenirEntreDates(DateTime debut, DateTime fin);

  /// Tasks generated by a given reminder (linked via `rappelOrigineId`).
  Future<List<Tache>> obtenirParRappel(String rappelOrigineId);

  Future<void> sauvegarder(Tache tache);

  /// Soft-deletes the task.
  Future<void> supprimer(String id);
}
